- pkg/common/chaos/agent.go
- pkg/common/chaos/project.go
- pkg/common/chaos/register.go
- pkg/common/chaos/workflow.go
- pkg/common/k8s/pod.go
- pkg/common/product.go
- pkg/constants/constants.go
Now an agent can be registered for the litmus portal using
```
litmusctl agent register command
```
Signed-off-by: arkajyotiMukherjee <arkajyoti.mukherjee@mayadata.io>
> Agent register functionality completed

- README.md
- pkg/common/chaos/agent.go
- pkg/common/chaos/project.go
- pkg/common/chaos/register.go
- pkg/common/platform.go
- pkg/constants/constants.go
Signed-off-by: arkajyotiMukherjee <arkajyoti.mukherjee@mayadata.io>
> minor code cleanup: removing unnecessary logs to the console

- README.md
- pkg/constants/constants.go
- scripts/build.sh
Addresses issue: https://github.com/litmuschaos/litmus/issues/2575
Signed-off-by: arkajyotiMukherjee <arkajyoti.mukherjee@mayadata.io>
> added more platforms types for litmusctl

- .github/workflows/main.yml
- .github/workflows/push.yml
- .gitignore
- Makefile
- scripts/build.sh
Signed-off-by: Raj Das <mail.rajdas@gmail.com>
> Deploying litmusctl bins to s3 bucket

- pkg/cmd/agent/agent.go
- pkg/cmd/agent/connect/connect.go
- pkg/cmd/litmusctl/litmusctl.go
- pkg/common/apply.go
- pkg/common/chaos/agent.go
- pkg/common/chaos/register.go
- pkg/common/input.go
- pkg/common/k8s/access.go
- pkg/common/k8s/client.go
- pkg/common/k8s/namespace.go
- pkg/common/k8s/pod.go
- pkg/common/k8s/sa.go
- pkg/common/platform.go
Add kubeconfig flag to litmusctl
> Add kubeconfig flag to litmusctl

- README.md
> version upgrade to v0.2.0

- .gitignore
- README.md
- Usage.md
- main.go
Minor fix of litmusctl version
> Minor fix of litmusctl version

- README.md
- Usage.md
- Usage_v0.2.0.md
adding compatible versions
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>
> adding compatible versions for litmusctl

- .github/workflows/codeql-analysis.yml
Adding security scanning workflow(codeql-analysis)
> Adding security scanning workflow(codeql-analysis)

- README.md
- Usage.md
- Usage_interactive.md
Adding interactive usage doc for litmusctl
> Adding interactive usage doc for litmusctl

- README.md
Issue-https://github.com/litmuschaos/litmusctl/issues/24
> Update README.md for the installation link

- README.md
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>
> update-bucket link

- go.mod
- go.sum
- pkg/apis/auth.go
- pkg/apis/project.go
- pkg/cmd/config/setAccount.go
Signed-off-by: Jonsy13 <vedant.shrotria@chaosnative.com>
> Added logic for parsing username from token

- pkg/apis/auth.go
- pkg/apis/project.go
- pkg/utils/constants.go
This PR fixes API path for auth APIs
Signed-off-by: SarthakJain26 <sarthak@chaosnative.com>
> Fixed API path for auth APIs

- pkg/apis/agent.go
- pkg/k8s/operations.go
Signed-off-by: Jonsy13 <vedant.shrotria@chaosnative.com>
**This PR will add some minor fixes in litmusctl.**
> Added some fixes for litmusctl

- README.md
Adding 0.7.0 and 0.6.0 installation link to readme
> Update README.md of litmusctl

- README.md
> Adding download link   for litmusctl v0.9.0 in readme

- pkg/apis/upgrade.go
- pkg/cmd/upgrade/agent.go
- Added proper error messages for upgrade agent
> Added proper error messages for upgrade agent

- README.md
Signed-off-by: Adarshkumar14 <adarsh.kumar@harness.io>
> Updating readme for litmusctl-0.10.0

- pkg/cmd/get/agents.go
- pkg/cmd/get/projects.go
> refactor: Reword field names in output to be consistent

- pkg/cmd/connect/agent.go
- Added code to print error message in log for connect agent
> Added code to print error message in log for connect agent

- pkg/apis/workflow.go
- pkg/cmd/get/get.go
- pkg/cmd/get/workflows.go
> feat(workflows): Add `get workflows` command

- pkg/apis/upgrade.go
- pkg/apis/workflow.go
Improved error handling logic for upgrade agent
> Improved error handling logic for upgrade agent

- pkg/cmd/describe/workflow.go
- pkg/cmd/disconnect/agent.go
Signed-off-by: Sarthak Jain <sarthak.jain@harness.io>
- Added error handling for describe workflow and disconnect agent command
> Added error handling for describe workflow and disconnect agent command

- README.md
- Usage.md
- Usage_interactive.md
Signed-off-by: Vedant <vedant.srotria@harness.io>
> Added changes for litmusctl readme update

- README.md
Signed-off-by: Vedant <vedant.srotria@harness.io>
> Added minor fix for binary downloads table

- pkg/apis/upgrade.go
- pkg/cmd/connect/agent.go
- pkg/cmd/upgrade/agent.go
- pkg/k8s/operations.go
- Added changes for error handling in litmusctl apply manifest logic
> Added changes for error handling in litmusctl apply manifest logic

- go.mod
- go.sum
Upgraded chaos operator version 
Signed-off-by: Sarthak Jain <sarthak.jain@harness.io>
> Updated chaos-operator version

- README.md
Updated compatibility and installation matrix in readme
> Updated compatibility and installation matrix in readme

- pkg/cmd/get/get.go
Just a typo that is really bugging me.
> Typo in get.go

- README.md
Updated readme with 0.14.0 download link, and updated compatibility matrix.
> Updated readme with 0.14.0 release

- pkg/cmd/config/setAccount.go
> Fixes non-interactive mode in set-account command

- .github-workflow-script
- .github/workflows/build.yml
- .pre-commit
- DEVELOPMENT.md
- pkg/cmd/get/environment.go
closes #196 
- Automated testing and pre-commit hook integration to ensure code quality and adherence to linting standards.
- Added a GitHub Actions workflow file (`build.yml`) to facilitate automated testing and pre-commit hook execution.
- Created a custom script (`.github-workflow-script`) to extract specific steps from the workflow file that contain the `COMMIT_HOOKS` environment variable set to "pre-commit".
- The GitHub Actions workflow defined in `build.yml` is triggered upon pull requests targeting the "master" branch.
- The workflow includes a job named "build" that sets up the Go environment, performs Go formatting checks, runs linting checks using golangci-lint, and builds the project.
- The `gofmt` check step is conditioned by the presence of the `COMMIT_HOOKS` environment …
> Pre commit Hook added.  

- pkg/cmd/get/experiments.go
closes #218
Added logic to check for output format before moving to prompt-ui
> non-interactive output for get experiment

- pkg/cmd/update/password.go
This pr fixes the update password command.
fixes #270
> fix: update password command

- pkg/cmd/config/setAccount.go
**Adds Initial Login check and prompt user to update the default password**
> feat: add initial login check

- Usage_0.23.0.md
- Usage_interactive.md
- pkg/cmd/config/setAccount.go
Updated docs to demonstrate usage of  `litmusctl update password` command
> docs: added usage for ` update password ` command
