pkg/apis/agent.go
pkg/cmd/connect/agent.go
pkg/cmd/connect/connect.go
pkg/cmd/delete/agent.go
pkg/cmd/delete/delete.go
pkg/cmd/disconnect/agent.go
pkg/cmd/disconnect/disconnect.go
pkg/cmd/get/agents.go
pkg/cmd/root/root.go

This PR adds the following changes,
- a command to delete (read delete and disconnect) a ChaosAgent present in the project.
- adds the field `isRegistered` in the output of `get agents` command.
- refactors the `create agent` command to `connect agent` for consistency.

feat(agents): Add delete agent command and refactor other agent commands

---

pkg/apis/workflow.go
pkg/cmd/get/get.go
pkg/cmd/get/workflowruns.go

feat(workflows): Add `get workflowruns` command

---

pkg/apis/workflow.go
pkg/cmd/delete/delete.go
pkg/cmd/delete/workflow.go
pkg/cmd/describe/describe.go
pkg/cmd/describe/workflow.go
pkg/cmd/root/root.go

feat(workflows): Add `delete workflow` and `describe workflow` commands

---

Usage.md
Usage_interactive.md

This PR adds the following changes in the usage documentation for litmusctl.
- Refactor `create agent` to `connect agent`.
- Add `REGISTRATION` field in `get agents`.
- Add `disconnect agents` command under additional commands.
- Add instructions for `create workflow` command.
- Add other workflow commands viz. `get`, `delete`, and `describe` under additional commands.

docs(agents|workflows): Update usage documentation

---

README.md
Usage.md
Usage_interactive.md
pkg/agent/ops.go
pkg/apis/agent.go
pkg/apis/upgrade.go
pkg/apis/workflow.go
pkg/cmd/connect/agent.go
pkg/cmd/connect/connect.go
pkg/cmd/create/create.go
pkg/cmd/create/workflow.go
pkg/cmd/delete/delete.go
pkg/cmd/delete/workflow.go
pkg/cmd/describe/describe.go
pkg/cmd/describe/workflow.go
pkg/cmd/disconnect/agent.go
pkg/cmd/disconnect/disconnect.go
pkg/cmd/get/agents.go
pkg/cmd/get/get.go
pkg/cmd/get/workflowruns.go
pkg/cmd/get/workflows.go
pkg/cmd/upgrade/agent.go
pkg/cmd/upgrade/upgrade.go
pkg/k8s/operations.go

Updated logs and commands with new terminology:
```
litmusctl connect agent -> litmusctl connect chaos-delegate
litmusctl disconnect agent -> litmusctl disconnect chaos-delegate
litmusctl get agents -> litmusctl get chaos-delegates
litmusctl create workflow -> litmusctl create chaos-scenario
litmusctl delete workflow -> litmusctl delete chaos-scenario
litmusctl describe workflow -> litmusctl describe chaos-scenario
litmusctl get workflows -> litmusctl get chaos-scenarios
litmusctl get workflowruns -> litmusctl get chaos-scenario-runs 
litmusctl upgrade agent -> litmusctl upgrade chaos-delegate
```
Signed-off-by: Sarthak Jain <sarthak.jain@harness.io>

Update commands and logs with new terminology

---

pkg/apis/workflow.go
pkg/cmd/config/setAccount.go
pkg/cmd/version/version.go
pkg/utils/constants.go

Added compatibility matrix and API to fetch GQL server version

Added compatibility matrix and API to fetch GQL server version

---

scripts/build.sh

The binaries available for download for Windows currently ship the binary as `litmusctl` (with no extension). While this is expected on Linux/macOS (where executables have no extension), it seems that Windows has trouble running/recognizing executable files that have no extension. Windows users currently need to rename the file manually to be able to execute it.
This PR modifies the build script to add `.exe` extension for Windows build artifacts where it is expected.

Add .exe extension to binaries on Windows

---

pkg/agent/platform.go

When attempting to install a ChaosDelegate onto a cluster with no nodes, the automatic platform detection methods for AWS and GKE will panic due to trying to access the first element of a zero-length slice.
This fix assumes that it is intended to allow users to install a ChaosDelegate into a cluster with no nodes. Alternatively, if this is not the case, another solution is to add a check for nodes existence before anything else.

Avoid panic during platform discovery with no nodes

---

pkg/cmd/connect/agent.go

The current help text for `--tolerations` is duplicated from the `--kubeconfig` option right before it. This PR sets appropriate help text for the flag, with an example based on the definition of the `Toleration` struct:
https://github.com/litmuschaos/litmusctl/blob/eaf8030d76da8f7e0f6642131daae4cb60a611ef/pkg/types/agent_types.go#L34-L40

Fix tolerations help text in ChaosDelegate connection

---

pkg/utils/workflow.go

Fixes issue #113 and aligns the `litmusctl create chaos-scenario` with the ChaosCenter functionality around checking for experiment `weights` and defining default values even when there are no experiments present ( as may be the case when using templated workflows).

litmsuctl create scenario command independent of install-chaos-experiments step

---

pkg/utils/workflow.go
scripts/build.sh

This PR fixes issue #116. It verifies if manifests has the `name` or the `generateName` attribute to assigned it to the create-scenario `chaosWorkflowRequest` accordingly.
In case the manifest has the `generateName` attribute it would create a random alphanumeric postfix string and concatenate it to the `name`. It will also delete the  `generateName` attribute from the manifest before submitting it to the API.

Litmusctl checks existence of workflow name before scheduling & add the same if not present already

---

.github/workflows/push.yml

Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Resolve #141 
Update `.github/workflows/push.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
```
**TO-BE**
```yaml
run: echo "branch=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
```

Replace deprecated command with environment file

---

pkg/apis/environment/environment.go
pkg/apis/experiment/experiment.go
pkg/apis/infrastructure/infra.go
pkg/apis/project.go
pkg/cmd/config/setAccount.go
pkg/cmd/create/environment.go
pkg/cmd/get/infra.go
pkg/config/ops.go
pkg/types/api_types.go
pkg/types/config_types.go
pkg/utils/common.go

This PR will add serverEndpoint in the litmusconfig file which can be configured as per the development setup. serverEndpoint is the endpoint where graphql server is running.
``` accounts:
- users:
- expires_in: "1697525696"
token: <jwt_token>
username: admin
endpoint: http://localhost:3000
serverEndpoint: http://localhost:8080
apiVersion: v1
current-account: http://localhost:3000
current-user: admin
kind: Config 
```

added changes to add server endpoint

---

Usage_0.23.0.md
go.mod
pkg/apis/environment/environment.go
pkg/apis/environment/query.go
pkg/cmd/get/environment.go
pkg/cmd/get/projects.go
pkg/cmd/list/environment.go
pkg/cmd/list/list.go
pkg/cmd/root/root.go

refers issue #164
Addition of new commands :
```
litmusctl get chaos-environment --project-id="" --environment-id=""
litmusctl list chaos-environment --project-id=""
```

Get chaos environments command

---

pkg/cmd/get/projects.go

closes #183
Added a little customized error message if the start index is greater than the total projects. This shall give a more appropriate error message rather than throwing a index out of bound error.

Fix : Index out of bound error for get projects command

---

pkg/cmd/version/version.go

closes issue #181
add check for version environment variable for `litmusctl version`
current output if variable is not set
```
litmusctl version
Error: CLIVersion environment variable is not set.
```

Version Command : add check if the environment variable is not set

---

pkg/cmd/root/root.go
pkg/cmd/update/update.go

Added upgrade command to change version of the litmusctl binary, works like `sudo litmusctl update 1.1.0`, tested on linux arm64 architecture. It works for every version that exists, meaning not only it can upgrade but downgrade as well, but the command upgrade is already taken hence I chose update.
Fixes [#3307](https://github.com/litmuschaos/litmus/issues/3307)

Added a new command to change version

---

pkg/cmd/get/projects.go

closes #192
fixed the output flag for the get projects which was not getting recognized in the code.

fix : output flag for get projects 

---

Usage_0.23.0.md
pkg/apis/environment/environment.go
pkg/apis/environment/query.go
pkg/apis/environment/types.go
pkg/cmd/delete/delete.go
pkg/cmd/delete/environment.go

Currently there is no command to delete the chaos environment. This feature will aim to add command to delete chaos environments based on the id provided.

feat:delete environment command

---

pkg/apis/probe/probe.go
pkg/apis/probe/types.go
pkg/cmd/delete/delete.go
pkg/cmd/delete/probe.go

Add a new feature/command to delete probe.
`litmusctl delete probe --project-id="" --probe-id=""`

Probe delete command

---

pkg/apis/project.go
pkg/cmd/get/projects.go

New changes was breaking the get project command. This will fix this

Fix for new schema changes

---

Usage_0.23.0.md
Usage_interactive.md
pkg/apis/infrastructure/query.go
pkg/apis/request.go
pkg/apis/upgrade.go
pkg/cmd/connect/infra.go
pkg/k8s/operations.go

- Fixed referer header issue
- Used client-go for chaos infra connection instead of kubectl apply

Fixed referer header issue, used client-go for chaos infra connection instead of kubectl apply

---

pkg/cmd/root/root.go
pkg/cmd/update/password.go
pkg/cmd/update/update.go
pkg/types/api_types.go
pkg/utils/constants.go

**### Description:**
Introduced `litmusctl update password` command,
User can now update their passwords using litmusctl

feat: added `update password` command

---

pkg/apis/project.go

This PR fixes the error on fetching projects when there are no projects created by user.
Fixes #264 
This PR is dependent on this [PR](https://github.com/litmuschaos/litmus/pull/5011) in the main repo.

fix: error on fetching projects when there are no projects
